name: Build and deploy Python app to Azure Web App - app-interviewrafaelc1f

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Create and start virtual environment
        working-directory: ./back-end/web-api
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: ./back-end/web-api
        run: |
          pip install -r requirements.txt
      
      # - name: Run Application
      #   working-directory: ./back-end/web-api
      #   run: python app.py

      # - name: Update database
      #   working-directory: ./back-end/web-api
      #   run: python setup.py

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'app-interviewrafaelc1f'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F5EF14EFF2BE4137B5588069167D8AC5 }}
          startup-file: 'startup.sh'

      # - name: Run Application on Azure
      #   run: az webapp ssh --name app-interviewrafaelc1f --resource-group rg-sre-user-02 --command "python app.py"

      - name: Update database on Azure
        run: az webapp ssh --name app-interviewrafaelc1f --resource-group rg-sre-user-02 --command "python setup.py"
        env: 
          NAME: DatabaseUpdate
